apps:
  - name: movie
    image: jawi95/movieapi:latest
    containerPort: 8000
    nodePort: 30081
    env:
      DATABASE_URI: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
      CAST_SERVICE_HOST_URL: http://cast-service:8000/api/v1/casts/
  - name: cast
    image: jawi95/castapi:latest
    containerPort: 8000
    nodePort: 30082
    env:
      DATABASE_URI: postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev

databases:
  - name: movie-db
    username: movie_db_username
    password: movie_db_password
    database: movie_db_dev
  - name: cast-db
    username: cast_db_username
    password: cast_db_password
    database: cast_db_dev

nginx:
  image: nginx:latest
  port: 8080
  nodePort: 30083
  domain: my-vm.abrdns.com
