{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  selector:
    app: {{ .name }}-service
  ports:
    - protocol: TCP
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      #nodePort: {{ .nodePort }}
  type: NodePort
---
{{- end }}
